builds:
  - main: ./cmd/ngrokcd
    binary: ngrokcd
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
    goarm:
      - 5

# Make release files look nice
archive:
  replacements:
    386: 32-bit
    amd64: 64-bit
  format: tar.gz
  files:
    - none*

# Do not publish the release yet
release:
  draft: true
  name_template: "v{{.Version}}"
