on: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/alyyousuf7/ngrok-custom-domain
    steps:
      - checkout
      - run:
          name: Release with goreleaser
          command: curl -sSL git.io/goreleaser | bash

workflows:
  version: 2
  build-and-release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
